# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarviUi(object):
    def setupUi(self, jarviUi):
        jarviUi.setObjectName("jarviUi")
        jarviUi.resize(741, 461)
        self.centralwidget = QtWidgets.QWidget(jarviUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 831, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/4th Sem downloads 2.0/Frame 2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 400, 108, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(105, 66, 220);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 50%;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 400, 108, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(105, 66, 220);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 50%;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 190, 371, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 10, 171, 70))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #5229CB;")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 10, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #8F6AFF;")
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 120, 130, 51))
        self.textBrowser.setStyleSheet("background-color: rgb(234, 232, 254);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(370, 120, 130, 51))
        self.textBrowser_2.setStyleSheet("background-color: rgb(234, 232, 254);\n"
"background-color: rgb(255, 248, 248);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(150, 239, 371, 141))
        self.textBrowser_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 90, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 90, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        jarviUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarviUi)
        QtCore.QMetaObject.connectSlotsByName(jarviUi)

    def retranslateUi(self, jarviUi):
        _translate = QtCore.QCoreApplication.translate
        jarviUi.setWindowTitle(_translate("jarviUi", "MainWindow"))
        self.pushButton_3.setText(_translate("jarviUi", "EXIT"))
        self.pushButton_4.setText(_translate("jarviUi", "RUN"))
        self.label_4.setText(_translate("jarviUi", ""))
        self.label_8.setText(_translate("jarviUi", "VIRTUAL"))
        self.label_9.setText(_translate("jarviUi", "ASSISTANT"))
        self.label_6.setText(_translate("jarviUi", "    TIME"))
        self.label_7.setText(_translate("jarviUi", " DATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarviUi = QtWidgets.QMainWindow()
    ui = Ui_jarviUi()
    ui.setupUi(jarviUi)
    jarviUi.show()
    sys.exit(app.exec_())
